spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdb
    username: root
    password: rootuser
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    root: INFO
    com.security.auth.config: DEBUG
    org.springdoc: WARN
    org.springframework.web.method: WARN


springdoc:
#  override-with-generic-response: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


jwt:
  secret: "your-very-long-secret-key-256-bit-or-more" # 256비트 이상!
  access-token-validity-in-seconds: 3600
